import React from 'react';
import { ChatMessage as ChatMessageType, MessageRole } from '../types';
import CatIcon from './icons/CatIcon';

interface ChatMessageProps {
  message: ChatMessageType;
}

const ChatMessage: React.FC<ChatMessageProps> = ({ message }) => {
  const isModel = message.role === MessageRole.MODEL;

  // Check for 'meow' to trigger animation
  const hasMeow = isModel && message.text.toLowerCase().includes('meow');

  return (
    <div className={`flex items-start gap-3 my-4 animate-slide-in-fade ${isModel ? 'justify-start' : 'justify-end'}`}>
      {isModel && (
        <div className="flex-shrink-0 w-8 h-8 rounded-full bg-slate-700 flex items-center justify-center">
          <CatIcon 
            className="w-5 h-5 text-cyan-400" 
            animation={hasMeow ? 'twitch' : undefined}
          />
        </div>
      )}
      <div className={`max-w-xs md:max-w-md lg:max-w-lg rounded-2xl shadow-lg overflow-hidden ${
          isModel
            ? 'bg-slate-700 text-slate-200 rounded-tl-none'
            : 'bg-cyan-600 text-white rounded-br-none'
        }`}
      >
        {message.imageUrl && (
          <img 
            src={message.imageUrl} 
            alt={message.text || "Generated by AI"} 
            className="w-full h-auto object-cover bg-white" 
          />
        )}
        {message.text && (
            <p className="whitespace-pre-wrap p-3">{message.text}</p>
        )}
      </div>
    </div>
  );
};

export default ChatMessage;
